# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# The assistant project unique identifier
# This default value must be replaced with a unique assistant name within your deployment
assistant_id: 20230904-233634-frigid-octree

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

pipeline:
# No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
# If you'd like to customize it, uncomment and adjust the pipeline.
# See https://rasa.com/docs/rasa/tuning-your-model for more information.

#--------------- LLM and generative capablity
# https://rasa.com/docs/rasa/installation/rasa-pro/installation/
# Step 1: install google cloud cli
# gcloud auth activate-service-account --key-file=${KEYFILE}
# gcloud auth configure-docker europe-west3-docker.pkg.dev
# docker pull europe-west3-docker.pkg.dev/rasa-releases/rasa-plus/rasa-plus
# Step 2: To add Generative features uncomment below 3 lines works with rasa pro

  # - name: rasa_plus.ml.LLMIntentClassifier
  #   llm:
  #     model_name: "text-davinci-003"
      # temprature: 0.7
  # - name: "MitieEntityExtractor"
  - name: "SpacyNLP"
  # language model to load
    model: "en_core_web_md"
    case_sensitive: False
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
    constrain_similarities: true
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
    constrain_similarities: true
  - name: FallbackClassifier
    threshold: 0.3
    ambiguity_threshold: 0.1

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
  - name: MemoizationPolicy
  - name: RulePolicy
  - name: UnexpecTEDIntentPolicy
    max_history: 5
    epochs: 100
  - name: TEDPolicy
    max_history: 5
    epochs: 100
    constrain_similarities: true


# language-classifier:
#   - name: "rasa.nlu.components.LanguageModelTokenizer"
#   - name: "rasa.nlu.classifiers.language.DucklingHTTPExtractor"
